// ═══════════════════════════════════════════════════════════════
// Sidebar Navigation — DERIVED from the module registry (ADR-0005)
//
// This file used to BE the navigation: a hardcoded 165-line array that had to be
// mirrored by hand into tests/e2e/app-routes.ts, and had drifted from it.
// It is now a presentation adapter: the registry owns labels, hrefs, order and
// flags; this file only turns icon NAMES into lucide components, because the
// registry must stay importable from non-React contexts (the e2e route matrix).
//
// To add a surface, add it to src/lib/modules/registry.ts. Do not edit this file
// unless you are adding an icon.
// ═══════════════════════════════════════════════════════════════

import {
  Terminal, FileText, Database, Clock, Shield, Zap,
  Cpu, Activity, Layers, HardDrive, Wrench, ListTodo, Globe, Globe2,
  ScrollText, Sparkles, Rocket, Volume2, Mic, GitBranch,
  RotateCcw, ShieldCheck, Lock, Code,
  BookOpen, Bot, MessageCircle,
  AudioLines, Settings2, Network, BarChart3, Trophy, Telescope, Workflow,
  FileStack,
} from "lucide-react";

import type { AccentColor } from "@/types/hermes";
import type { FeatureFlag } from "@/lib/feature-flags";
import { MODULES } from "@/lib/modules/registry";
import type { IconName, NavLink as ModuleNavLink } from "@/lib/modules/types";

// ── Types ──────────────────────────────────────────────────────

export interface SidebarLink {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  href: string;
  color: AccentColor;
  subLinks?: { label: string; href: string }[];
  /** When set, the link is hidden while that feature flag is disabled. */
  featureFlag?: FeatureFlag;
}

export interface SidebarSection {
  label: string;
  links: SidebarLink[];
}

export interface ConfigGroup {
  label: string;
  defaultOpen?: boolean;
  links: SidebarLink[];
}

// ── Icon resolution ────────────────────────────────────────────

/**
 * Exhaustive over IconName, so adding a name to the registry without an icon
 * here is a compile error rather than a blank space in the sidebar.
 */
const ICONS: Record<IconName, React.ComponentType<{ className?: string }>> = {
  Zap, Clock, Database, ScrollText,
  Rocket, Workflow, Terminal, MessageCircle,
  Bot, FileText, Wrench, Sparkles,
  BarChart3, Trophy, Telescope, FileStack,
  BookOpen, Globe, Cpu, Lock,
  RotateCcw, Activity, Layers, HardDrive,
  Globe2, Code, Shield, ShieldCheck,
  AudioLines, Mic, Volume2, GitBranch,
  ListTodo, Network, Settings2,
};

function toSidebarLink(link: ModuleNavLink): SidebarLink {
  return {
    icon: ICONS[link.icon],
    label: link.label,
    href: link.href,
    color: link.color,
    ...(link.subLinks ? { subLinks: link.subLinks } : {}),
    ...(link.featureFlag ? { featureFlag: link.featureFlag } : {}),
  };
}

// ── Derived navigation ─────────────────────────────────────────

/**
 * Sections in registration order. Modules may contribute to a section name that
 * another module also uses; those merge, so a future module can add a link to
 * "Orchestration" without core knowing about it.
 */
export const mainSections: SidebarSection[] = (() => {
  const byLabel = new Map<string, SidebarLink[]>();
  const order: string[] = [];
  for (const mod of MODULES) {
    for (const section of mod.nav ?? []) {
      if (!byLabel.has(section.label)) {
        byLabel.set(section.label, []);
        order.push(section.label);
      }
      byLabel.get(section.label)!.push(...section.links.map(toSidebarLink));
    }
  }
  return order.map((label) => ({ label, links: byLabel.get(label)! }));
})();

/** Shown under "Config Settings", above "All Settings" (file editors + env). */
export const configSettingsPinnedLinks: SidebarLink[] = MODULES.flatMap((m) =>
  (m.configPinned ?? []).map(toSidebarLink),
);

export const configGroups: ConfigGroup[] = MODULES.flatMap((m) =>
  (m.configGroups ?? []).map((g) => ({
    label: g.label,
    ...(g.defaultOpen !== undefined ? { defaultOpen: g.defaultOpen } : {}),
    links: g.links.map(toSidebarLink),
  })),
);
