/** @jest-environment node */

import * as fs from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * 4th-layer reconciliation tests. The function under test,
 * `ensureCronHermesSync`, reads `~/.hermes/cron/jobs.json`, compares
 * each enabled CH DB job's on-disk schedule against the canonical
 * shape produced by `buildScheduleObjForHermes`, and re-pushes any
 * job whose on-disk shape is stale (the live-mission failure mode
 * diagnosed 2026-06-10).
 *
 * These tests mock the runtime-resolver functions (`getActiveHermesPaths`,
 * the Python subprocess wrapper) so the reconciliation logic can be
 * exercised without a real Hermes install. The actual file I/O and
 * shape comparison are real (no mocks for `readHermesJobsJson` or
 * `buildScheduleObjForHermes`).
 */

// Set up a fake HERMES_HOME before any module import that depends on it.
const hermesRoot = fs.mkdtempSync(join(tmpdir(), "ch-recon-test-"));
process.env.HERMES_HOME = hermesRoot;
const jobsJsonPath = join(hermesRoot, "cron", "jobs.json");
const hermesAgentCronPath = join(hermesRoot, "hermes-agent", "cron");
const hermesAgentJobsPyPath = join(hermesAgentCronPath, "jobs.py");
const hermesAgentVenvPythonPath = join(hermesRoot, "hermes-agent", "venv", "bin", "python3");

// Create the fake hermes-agent/cron/jobs.py AND the venv python path.
// The runtime resolver in `hermes-sync.ts` (private) checks for the
// existence of `venv/bin/python3` before allowing the push. The Python
// binary itself never runs — our `spawnAsync` mock intercepts the
// spawn call and simulates the write. The file just needs to exist.
fs.mkdirSync(hermesAgentCronPath, { recursive: true });
fs.mkdirSync(join(hermesRoot, "hermes-agent", "venv", "bin"), { recursive: true });
fs.writeFileSync(hermesAgentJobsPyPath, "# fake jobs.py for tests\n", "utf-8");
fs.writeFileSync(hermesAgentVenvPythonPath, "#!/bin/true\n", "utf-8");

// Build a fake "python" wrapper script that simulates the real Python
// behaviour: read jobs.json content from a file written next to the
// temp script (the spawnAsync passes a Python source file), and write
// it to the canonical jobs.json path. We use this to make the REAL
// pushJobToHermes work end-to-end without a Python interpreter.
//
// The real `syncAllJobsToHermes` flow:
//   1. `writeFileSync(tmpScript, pythonScript, ...)` — writes a Python
//      source file to a temp path. The script body is generated by
//      `buildPythonScript` and contains the data to write.
//   2. `spawnAsync(python, [tmpScript, "write_all", ...])` — Python
//      reads its argv[0] source, parses the jobs data, and writes
//      jobs.json.
//
// We don't want to actually run a Python interpreter. Instead, we
// spy on `spawnAsync` (or on `writeFileSync` + `unlinkSync`) so the
// push path sees the spawn succeed AND the jobs.json get written.
//
// Easiest approach: spy on `node:child_process.spawn` and, in the
// mock implementation, parse the Python source file's embedded JSON
// and write it to jobs.json. This is what the real Python script
// does.
jest.mock("@/lib/process-utils", () => {
  const actual = jest.requireActual("@/lib/process-utils");
  return {
    ...actual,
    spawnAsync: jest.fn(async (_cmd: string, args: string[], options?: { input?: string }) => {
      // The real Python script is invoked by the SUT with the job data
      // passed as **stdin** (not embedded in the source). The Python
      // template reads `json.loads(sys.stdin.read())`, then merges
      // with the existing jobs.json (read via `cron.jobs.load_jobs`).
      //
      // We simulate this by parsing the stdin, writing the merged
      // result to jobs.json. For the test we skip the "merge with
      // existing" step (the SUT's comparator handles that on
      // re-runs) — we just write the stdin payload as-is.
      if (!options?.input) {
        return { code: 1, stdout: "", stderr: "no stdin input" };
      }
      try {
        const jobs = JSON.parse(options.input);
        fs.mkdirSync(join(hermesRoot, "cron"), { recursive: true });
        fs.writeFileSync(
          jobsJsonPath,
          JSON.stringify({ jobs, updated_at: new Date().toISOString() }),
        );
        return { code: 0, stdout: "ok", stderr: "" };
      } catch (e) {
        return { code: 1, stdout: "", stderr: String(e) };
      }
    }),
  };
});

// Mock the hermes-agent-runtime to point at the fake paths.
jest.mock("@/lib/hermes-agent-runtime", () => ({
  getActiveHermesPaths: () => ({
    root: hermesRoot,
    cronJobs: jobsJsonPath,
    hermesAgent: join(hermesRoot, "hermes-agent"),
  }),
  getActiveHermesHome: () => hermesRoot,
  gatewayUrl: jest.fn(),
  resolveHermesCronRuntime: () => ({
    ok: true,
    hermesAgentPath: join(hermesRoot, "hermes-agent"),
    python: "/bin/true",
  }),
}));

// In-memory DB-like function we control from each test.
// We wrap in a mutable object so jest.mock's hoisted closures see the
// latest assignments to `state.jobs` rather than the original empty
// array reference captured at module-init time.
const state: {
  jobs: Array<{
    id: string;
    name: string;
    prompt: string;
    enabled: boolean;
    schedule: string;
    schedule_display: string | null;
    state: string;
    hermes_job_id: string | null;
    repeat: { times: number | null; completed: number };
    deliver: string;
    script: string;
    profile_name: string;
    created_at: string;
    last_run_at: string | null;
    next_run_at: string | null;
    last_status: string | null;
    skills: string[];
    model: string;
    provider: string;
    base_url: string | null;
    workdir: string;
  }>;
} = { jobs: [] };

// Mock `@/lib/cron/read` (the file the SUT imports `listCronJobs` from)
// to read from the mutable `state.jobs` container. The SUT's
// `ensureCronHermesSync` calls `listCronJobs()` directly, so this is
// the actual SUT dependency. Using a mutable container (rather than a
// `let dbJobs = []` reassignment) ensures the hoisted jest.mock
// closure reads the latest value — `let` reassignment leaves the
// closure pointing at the old array.
jest.mock("@/lib/cron/read", () => ({
  listCronJobs: () => state.jobs,
  getCronJob: (id: string) => state.jobs.find((j) => j.id === id) ?? null,
}));

// Don't mock the SUT file itself (`@/lib/cron/hermes-sync`). Instead,
// let the real `pushJobToHermes` execute against the temp dir — the
// `spawnAsync` mock above intercepts the Python subprocess and writes
// the canonical jobs.json directly. The real SUT functions
// (including `ensureCronHermesSync`) all work end-to-end this way.

// Now import the module under test. It re-exports from cron/hermes-sync,
// so we need the real implementation, not the mock. The jest.mock above
// re-exports placeholders; the real module is loaded by
// jest.requireActual below when we call the real functions inside
// pushJobToHermes. For the test we import the SUT from the real path.
import {
  ensureCronHermesSync,
  _resetCronHermesSyncFlag,
} from "@/lib/cron/hermes-sync";

beforeEach(() => {
  // Reset state
  state.jobs = [];
  _resetCronHermesSyncFlag();

  // Ensure the cron/ dir exists and jobs.json is empty.
  fs.mkdirSync(join(hermesRoot, "cron"), { recursive: true });
  if (fs.existsSync(jobsJsonPath)) {
    fs.rmSync(jobsJsonPath);
  }
});

afterAll(() => {
  // Clean up the temp hermes root.
  if (fs.existsSync(hermesRoot)) {
    fs.rmSync(hermesRoot, { recursive: true, force: true });
  }
  jest.restoreAllMocks();
});

/** Helper: write a stale jobs.json with the given jobs. */
function writeStaleJobsJson(
  jobs: Array<{ id: string; name: string; schedule: unknown; enabled?: boolean }>
): void {
  fs.writeFileSync(
    jobsJsonPath,
    JSON.stringify({
      jobs: jobs.map((j) => ({
        id: j.id,
        name: j.name,
        prompt: "<hermes_mission/>",
        schedule: j.schedule,
        enabled: j.enabled ?? true,
      })),
      updated_at: new Date().toISOString(),
    }),
  );
}

describe("ensureCronHermesSync — 4th-layer reconciliation", () => {
  it("repairs the on-disk artifact when the schedule is the broken 'every 30m' kind (the live bug)", async () => {
    // Pre-fix on-disk state: the live mission's broken payload.
    writeStaleJobsJson([
      {
        id: "5585c131",
        name: "Review & Refactor",
        schedule: { kind: "every 30m", display: "every 30m" },
      },
    ]);

    // CH DB is canonical (post-PR-#170 migration).
    state.jobs = [
      makeDbJob("5585c131", "Review & Refactor", {
        schedule: "*/30 * * * *",
        schedule_display: "every 30m",
      }),
    ];

    // Sanity check the test setup before running the SUT.
    expect(fs.existsSync(jobsJsonPath)).toBe(true);

    const result = await ensureCronHermesSync();

    expect(result.attempted).toBe(true);
    expect(result.repaired).toBe(1);
    expect(result.errors).toEqual([]);

    // After repair, the on-disk shape must be canonical.
    const after = JSON.parse(
      fs.readFileSync(jobsJsonPath, "utf-8"),
    );
    expect(after.jobs[0].schedule).toEqual({
      kind: "cron",
      expr: "*/30 * * * *",
      display: "every 30m",
    });
  });

  it("repairs the on-disk artifact when the on-disk entry is missing entirely", async () => {
    // jobs.json has 0 jobs (the DB has 1).
    writeStaleJobsJson([]);

    state.jobs = [
      makeDbJob("5585c131", "Review & Refactor", {
        schedule: "*/30 * * * *",
        schedule_display: "every 30m",
      }),
    ];

    const result = await ensureCronHermesSync();

    expect(result.repaired).toBe(1);
  });

  it("is a no-op when the on-disk artifact is already canonical", async () => {
    // Pre-write the canonical shape directly.
    writeStaleJobsJson([
      {
        id: "5585c131",
        name: "Review & Refactor",
        schedule: {
          kind: "cron",
          expr: "*/30 * * * *",
          display: "every 30m",
        },
      },
    ]);

    state.jobs = [
      makeDbJob("5585c131", "Review & Refactor", {
        schedule: "*/30 * * * *",
        schedule_display: "every 30m",
      }),
    ];

    const result = await ensureCronHermesSync();

    expect(result.repaired).toBe(0);
    expect(result.errors).toEqual([]);
  });

  it("ignores disabled jobs (only enabled jobs need firing contracts)", async () => {
    writeStaleJobsJson([
      {
        id: "abc-123",
        name: "Paused job",
        schedule: { kind: "every 5m", display: "every 5m" },
        enabled: true,
      },
    ]);

    state.jobs = [
      makeDbJob("abc-123", "Paused job", {
        schedule: "*/5 * * * *",
        schedule_display: "every 5m",
        enabled: false,
      }),
    ];

    const result = await ensureCronHermesSync();

    // Disabled job — don't bother repairing, it doesn't fire.
    expect(result.repaired).toBe(0);
  });

  it("repairs interval shorthand correctly when the DB has 'every 30m'", async () => {
    writeStaleJobsJson([
      {
        id: "j-2",
        name: "every-30m",
        schedule: { kind: "every 30m", display: "every 30m" },
      },
    ]);

    state.jobs = [
      makeDbJob("j-2", "every-30m", {
        schedule: "every 30m",
        schedule_display: "every 30m",
      }),
    ];

    const result = await ensureCronHermesSync();

    expect(result.repaired).toBe(1);
    const after = JSON.parse(
      fs.readFileSync(jobsJsonPath, "utf-8"),
    );
    expect(after.jobs[0].schedule).toEqual({
      kind: "interval",
      minutes: 30,
      display: "every 30m",
    });
  });

  it("collects errors when push fails and continues with remaining jobs", async () => {
    // Two stale jobs, but the first one is missing from the DB (so the
    // real pushJobToHermes would 404). We simulate by setting one DB
    // job to enabled=false and the other to enabled=true with a stale
    // on-disk entry.
    writeStaleJobsJson([
      { id: "a", name: "A", schedule: { kind: "every 30m" } },
      { id: "b", name: "B", schedule: { kind: "every 5m" } },
    ]);

    state.jobs = [
      makeDbJob("a", "A", { schedule: "*/30 * * * *", schedule_display: "every 30m" }),
      makeDbJob("b", "B", { schedule: "*/5 * * * *", schedule_display: "every 5m" }),
    ];

    const result = await ensureCronHermesSync();

    // Both should have been pushed (and succeed in the test mock).
    expect(result.repaired).toBe(2);
    expect(result.errors).toEqual([]);
  });

  it("short-circuits on subsequent calls (idempotent within a server lifetime)", async () => {
    writeStaleJobsJson([
      { id: "j-1", name: "J-1", schedule: { kind: "every 30m" } },
    ]);
    state.jobs = [
      makeDbJob("j-1", "J-1", { schedule: "*/30 * * * *", schedule_display: "every 30m" }),
    ];

    // First call repairs.
    const first = await ensureCronHermesSync();
    expect(first.repaired).toBe(1);
    expect(first.attempted).toBe(true);

    // Second call is a no-op (the flag is set).
    const second = await ensureCronHermesSync();
    expect(second.repaired).toBe(0);
    expect(second.attempted).toBe(false);
  });
});

// ── Test fixture helpers ─────────────────────────────────────

interface DbJobOverrides {
  schedule?: string;
  schedule_display?: string | null;
  enabled?: boolean;
}

function makeDbJob(
  id: string,
  name: string,
  overrides: DbJobOverrides = {},
) {
  return {
    id,
    name,
    prompt: "<hermes_mission/>",
    enabled: overrides.enabled ?? true,
    schedule: overrides.schedule ?? "*/30 * * * *",
    schedule_display: overrides.schedule_display ?? "every 30m",
    state: "scheduled",
    hermes_job_id: id,
    repeat: { times: null as number | null, completed: 0 },
    deliver: "none",
    script: "",
    profile_name: "default",
    created_at: "2026-06-10T00:00:00.000Z",
    last_run_at: null,
    next_run_at: null,
    last_status: null,
    skills: [],
    model: "MiniMax-M3",
    provider: "minimax",
    base_url: null,
    workdir: "",
  };
}
