/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * @jest-environment node
 *
 * Bug regression test: the bash script generated by
 * `spawnHermesChatWithStatusCallback` (hermes.ts:236-271) had no
 * `EXIT` trap. Consequence: a SIGKILL of the bash script (host
 * OOM, parent process reaping, manual kill) left no status.json
 * at all, and MissionSync's orphan detection was the only path
 * to recovery — and it had its own gaps (fixed in the same PR).
 *
 * Fix: the generated script now installs an `EXIT` trap that
 * writes a synthetic failed status.json if no terminal status was
 * written by the success/failure branches. The trap fires for
 * ANY exit (normal, error, signal).
 */
import {
  existsSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
  chmodSync,
  mkdirSync,
  readFileSync,
} from "fs";
import { join } from "path";
import { tmpdir } from "os";

let tmpRoot: string;
let hermesRoot: string;
let missionsDir: string;

function findMissionScriptInScript(scriptText: string): boolean {
  // Look for the trap declaration shape. The fix installs a trap
  // on EXIT that writes a failed status file when the statusFile
  // doesn't already exist.
  return /\btrap\b/.test(scriptText) && /EXIT/.test(scriptText);
}

beforeAll(() => {
  tmpRoot = mkdtempSync(join(tmpdir(), "ch-bash-exit-trap-"));
  hermesRoot = join(tmpRoot, "hermes-fake");
  missionsDir = join(tmpRoot, "missions");
  mkdirSync(hermesRoot, { recursive: true });
  mkdirSync(missionsDir, { recursive: true });
  // Build a fake "hermes" binary that just sleeps forever. The
  // real binary would run the chat session; for this test we
  // don't need it to do anything — we just need a process to kill.
  const fakeHermes = join(hermesRoot, "fake-hermes.sh");
  writeFileSync(
    fakeHermes,
    "#!/bin/bash\nsleep 60\n",
  );
  chmodSync(fakeHermes, 0o755);
});

afterAll(() => {
  if (tmpRoot && existsSync(tmpRoot)) rmSync(tmpRoot, { recursive: true, force: true });
});

describe("spawnHermesChatWithStatusCallback — generated script", () => {
  it("installs an EXIT trap that writes a failed status.json", () => {
    const { spawnHermesChatWithStatusCallback } = require("@/lib/backends/hermes") as {
      spawnHermesChatWithStatusCallback: (input: {
        argv: string[];
        prompt: string;
        missionId: string;
        statusFile: string;
        outputFile: string;
        sessionFile: string;
        hermesHome: string;
      }) => number;
    };

    const missionId = "trap-test-1";
    const statusFile = join(missionsDir, `${missionId}.status.json`);
    const outputFile = join(missionsDir, `${missionId}.output.log`);
    const sessionFile = join(missionsDir, `${missionId}.session`);

    spawnHermesChatWithStatusCallback({
      argv: ["chat", "--quiet", "--source", "test"],
      prompt: "test prompt",
      missionId,
      statusFile,
      outputFile,
      sessionFile,
      hermesHome: hermesRoot,
    });

    // The script lives in os.tmpdir() (missionScriptPath)
    const os = require("os");
    const scriptPath = join(os.tmpdir(), `hermes_mission_${missionId}.sh`);
    expect(existsSync(scriptPath)).toBe(true);

    const script = readFileSync(scriptPath, "utf-8");
    // The generated script MUST contain an EXIT trap that writes
    // a failed status.json when no terminal status was written.
    expect(findMissionScriptInScript(script)).toBe(true);

    // The trap body should reference the status file and write
    // JSON with status="failed" — the same shape as the
    // success/failure branches.
    expect(script).toMatch(/status/);
    expect(script).toMatch(/"failed"/);
  });

  it("writes a failed status.json when hermes exits with a non-zero code (set -e path)", async () => {
    // End-to-end: spawn the real script via the same code path the
    // server uses, but use a fake hermes that exits non-zero. The
    // script's `set -e` aborts on the failure and the EXIT trap
    // fires. This is the COMMON case: hermes chat fails for any
    // reason (auth error, rate limit, bad model id) and the
    // success/failure branches write a status.json via the
    // existing if/else. We test the trap path with a hermes
    // binary that writes a status.json on a normal exit (so the
    // trap has nothing to do) — verifying the existing path.
    const { spawnHermesChatWithStatusCallback } = require("@/lib/backends/hermes") as {
      spawnHermesChatWithStatusCallback: (input: {
        argv: string[];
        prompt: string;
        missionId: string;
        statusFile: string;
        outputFile: string;
        sessionFile: string;
        hermesHome: string;
      }) => number;
    };

    const missionId = "trap-e2e-success";
    const statusFile = join(missionsDir, `${missionId}.status.json`);
    const outputFile = join(missionsDir, `${missionId}.output.log`);
    const sessionFile = join(missionsDir, `${missionId}.session`);

    // Build a hermes wrapper that writes a success status and
    // exits 0. This tests the normal happy path: the success
    // branch writes the status.json before the trap fires, so the
    // trap is a no-op. The script invokes `hermes` directly, so
    // we put the fake binary on PATH (the script inherits the
    // parent's env, so we just need hermesRoot to be the
    // first PATH entry).
    const fakeHermes = join(hermesRoot, "hermes");
    writeFileSync(
      fakeHermes,
      "#!/bin/bash\necho 'fake hermes run completed'\nexit 0\n",
    );
    chmodSync(fakeHermes, 0o755);

    // Temporarily prepend hermesRoot to PATH so the script's
    // `hermes` invocation finds our fake
    const prevPath = process.env.PATH;
    process.env.PATH = `${hermesRoot}${require("path").delimiter}${prevPath ?? ""}`;

    let pid: number;
    try {
      pid = spawnHermesChatWithStatusCallback({
        argv: ["chat", "--quiet", "--source", "test"],
        prompt: "test prompt",
        missionId,
        statusFile,
        outputFile,
        sessionFile,
        hermesHome: hermesRoot,
      });
    } finally {
      process.env.PATH = prevPath;
    }

    expect(pid).toBeGreaterThan(0);

    // Wait for the script to complete naturally
    const deadline = Date.now() + 10000;
    let found = false;
    while (Date.now() < deadline) {
      if (existsSync(statusFile)) {
        found = true;
        break;
      }
      await new Promise((r) => setTimeout(r, 100));
    }

    expect(found).toBe(true);
    const status = JSON.parse(readFileSync(statusFile, "utf-8"));
    // The success branch (existing code) writes the status.json
    expect(status.status).toBe("successful");
  }, 15000);

  it("writes a failed status.json via the EXIT trap when the script's success/failure branches don't run", async () => {
    // The trap fires whenever the script terminates. We force
    // the trap path by:
    // 1. Spawning the script.
    // 2. Pre-creating the SUCCESS/FAILURE status.json with an
    //    unusual sentinel (so the script's success/failure
    //    branches see "already there" and don't write).
    // 3. Killing the bash script with SIGTERM (catchable).
    //
    // Actually that doesn't work because the success/failure
    // branches overwrite the status file.
    //
    // Better: use a fake hermes that hangs. The script is
    // stuck on `hermes ...`. We send SIGTERM to the script
    // process group. Bash receives SIGTERM, the default
    // disposition is to exit, and the EXIT trap fires.
    const { spawnHermesChatWithStatusCallback } = require("@/lib/backends/hermes") as {
      spawnHermesChatWithStatusCallback: (input: {
        argv: string[];
        prompt: string;
        missionId: string;
        statusFile: string;
        outputFile: string;
        sessionFile: string;
        hermesHome: string;
      }) => number;
    };

    const missionId = "trap-e2e-sigterm";
    const statusFile = join(missionsDir, `${missionId}.status.json`);
    const outputFile = join(missionsDir, `${missionId}.output.log`);
    const sessionFile = join(missionsDir, `${missionId}.session`);

    // Fake hermes that hangs forever
    const fakeHermes = join(hermesRoot, "hermes");
    writeFileSync(
      fakeHermes,
      "#!/bin/bash\nsleep 300\n",
    );
    chmodSync(fakeHermes, 0o755);

    const prevPath = process.env.PATH;
    process.env.PATH = `${hermesRoot}${require("path").delimiter}${prevPath ?? ""}`;

    let pid: number;
    try {
      pid = spawnHermesChatWithStatusCallback({
        argv: ["chat", "--quiet", "--source", "test"],
        prompt: "test prompt",
        missionId,
        statusFile,
        outputFile,
        sessionFile,
        hermesHome: hermesRoot,
      });
    } finally {
      process.env.PATH = prevPath;
    }

    expect(pid).toBeGreaterThan(0);

    // Wait briefly for the script to start, then SIGTERM the
    // script's process group. Bash handles SIGTERM and runs the
    // EXIT trap before exiting.
    await new Promise((r) => setTimeout(r, 500));
    try {
      // SIGTERM the process group (negative pid) so the bash
      // script and any children all receive the signal
      process.kill(-pid, "SIGTERM");
    } catch {
      // may have already exited; fall back to direct kill
      try {
        process.kill(pid, "SIGTERM");
      } catch {
        // ignore
      }
    }

    // Wait for the trap to fire and the status file to appear
    const deadline = Date.now() + 5000;
    let found = false;
    while (Date.now() < deadline) {
      if (existsSync(statusFile)) {
        found = true;
        break;
      }
      await new Promise((r) => setTimeout(r, 100));
    }

    expect(found).toBe(true);
    const status = JSON.parse(readFileSync(statusFile, "utf-8"));
    expect(status.status).toBe("failed");
    expect(status.error).toBeDefined();
  }, 15000);
});
