// ═══════════════════════════════════════════════════════════════
// help-source.ts — reading the built Help corpus off disk
//
// public/help/ is generated by scripts/docs/build-site.mjs at prebuild and is
// git-ignored, so a fresh clone has none of it until the first build. Every
// function here therefore returns the empty value rather than throwing: the
// Help page's job when the corpus is absent is to say how to build it, and a
// loader that threw would take the whole render with it.
//
// Server only. It is imported by the Help page and by the root layout, both
// server components; the client gets the two small indexes as props.
// ═══════════════════════════════════════════════════════════════

import { existsSync, readFileSync } from "fs";
import { join, resolve, sep } from "path";

import {
  EMPTY_HELP_MANIFEST,
  isSafeHelpSlug,
  parseConcepts,
  parseHelpManifest,
  parseSearchIndex,
  type ConceptIndex,
  type HelpManifest,
  type HelpSearchEntry,
} from "./help-manifest";

/**
 * Where the corpus lives.
 *
 * PS_HELP_DIR overrides it, read at call time rather than at module load, so a
 * test or the isolated instance can point at a built corpus without a public/
 * in the checkout, and can move it between cases.
 */
export function helpRoot(): string {
  const override = process.env.PS_HELP_DIR;
  return override && override.trim() ? override : join(process.cwd(), "public", "help");
}

interface Cache {
  root: string;
  manifest?: HelpManifest;
  concepts?: ConceptIndex;
  search?: HelpSearchEntry[];
}

// Memoised per process: the layout reads the manifest on every request, and one
// readFileSync per process is the difference between that being free and being
// a syscall on every page view.
let cache: Cache = { root: "" };

function cacheFor(): Cache {
  const root = helpRoot();
  if (cache.root !== root) cache = { root };
  return cache;
}

/** Forget what was read. For tests, and for a dev watcher after a rebuild. */
export function resetHelpCache(): void {
  cache = { root: "" };
}

function readJson(name: string): unknown {
  const path = join(helpRoot(), name);
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    // Unreadable bytes, a half-written file mid-build, invalid JSON: all the
    // same answer, which is that there is no usable corpus right now.
    return null;
  }
}

export function loadHelpManifest(): HelpManifest {
  const c = cacheFor();
  if (!c.manifest) c.manifest = parseHelpManifest(readJson("manifest.json"));
  return c.manifest;
}

export function loadHelpConcepts(): ConceptIndex {
  const c = cacheFor();
  if (!c.concepts) c.concepts = parseConcepts(readJson("concepts.json"));
  return c.concepts;
}

export function loadHelpSearchIndex(): HelpSearchEntry[] {
  const c = cacheFor();
  if (!c.search) c.search = parseSearchIndex(readJson("search.json"));
  return c.search;
}

/** True when there is a corpus worth rendering. */
export function helpIsBuilt(): boolean {
  return loadHelpManifest().pages.length > 0;
}

/**
 * One page's HTML body, or null.
 *
 * Two belts, deliberately. The slug is refused BEFORE a path is built, because
 * the safest way to survive a traversal attempt is never to construct the path;
 * and the resolved path is then checked to be inside the fragments directory,
 * because a guard that only reads the input trusts its own regex more than it
 * should.
 */
export function loadHelpFragment(slug: string): string | null {
  if (!isSafeHelpSlug(slug)) return null;
  const fragments = join(helpRoot(), "fragments");
  const path = `${join(fragments, ...slug.split("/"))}.html`;
  const resolved = resolve(path);
  if (!resolved.startsWith(resolve(fragments) + sep)) return null;
  try {
    if (!existsSync(resolved)) return null;
    return readFileSync(resolved, "utf-8");
  } catch {
    return null;
  }
}

export { EMPTY_HELP_MANIFEST };
